// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "org.scala-lang.modules" % "scala-xml_2.12" % "1.0.6"
)
// LIBRARY_DEPENDENCIES_HASH fc970788a4bbfa960084855dee41965a77c55912
